// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIY1cHe8VKQkH_XxiDpJgmcn5JvYsslMg',
    appId: '1:691911452569:web:6b789e9661bed506629508',
    messagingSenderId: '691911452569',
    projectId: 'graduation-19097',
    authDomain: 'graduation-19097.firebaseapp.com',
    storageBucket: 'graduation-19097.firebasestorage.app',
    measurementId: 'G-DF6V7895KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaiTWvglhREczwNQMJe3Yx4103SSpfwGQ',
    appId: '1:691911452569:android:7eb1df098398cd6a629508',
    messagingSenderId: '691911452569',
    projectId: 'graduation-19097',
    storageBucket: 'graduation-19097.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlRn-AycDKrVSZkUJ-bLm9fHSQzdfJCws',
    appId: '1:691911452569:ios:8d34d7d5eeb6084f629508',
    messagingSenderId: '691911452569',
    projectId: 'graduation-19097',
    storageBucket: 'graduation-19097.firebasestorage.app',
    iosBundleId: 'com.example.therapy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlRn-AycDKrVSZkUJ-bLm9fHSQzdfJCws',
    appId: '1:691911452569:ios:8d34d7d5eeb6084f629508',
    messagingSenderId: '691911452569',
    projectId: 'graduation-19097',
    storageBucket: 'graduation-19097.firebasestorage.app',
    iosBundleId: 'com.example.therapy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIY1cHe8VKQkH_XxiDpJgmcn5JvYsslMg',
    appId: '1:691911452569:web:fed199dd71cf7f56629508',
    messagingSenderId: '691911452569',
    projectId: 'graduation-19097',
    authDomain: 'graduation-19097.firebaseapp.com',
    storageBucket: 'graduation-19097.firebasestorage.app',
    measurementId: 'G-9Q0GMPGDGW',
  );
}
